name: core

on:
  push:
    branches:
      - jp-test-bb-4
  pull_request:

jobs:
  unittests:
    name: unit_tests
    runs-on: macos-12
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: 'Install dependencies'
        run: ./ci/mac_ci_setup.sh
      - name: 'Run tests'
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
        run: ./bazelw test --test_output=all --config=remote-ci-macos --remote_header="x-buildbuddy-api-key=$BUILDBUDDY_API_KEY" //test/common/...
